language: node_js

node_js:
  - "0.12"

before_install:
  # Decrypt the private key
  - openssl aes-256-cbc -K $encrypted_94d9ccadd03a_key -iv $encrypted_94d9ccadd03a_iv -in .travis/ssh_key.enc -out ~/.ssh/id_rsa -d
  # Set the permission of the key
  - chmod 600 ~/.ssh/id_rsa
  # Start SSH agent
  - eval $(ssh-agent)
  # Add the private key to the system
  - ssh-add ~/.ssh/id_rsa
  # Copy SSH config
  - cp .travis/ssh_config ~/.ssh/config
  # Set Git config
  - git config --global user.name "Susen Zhao"
  - git config --global user.email prcstyler@gmail.com
  # Install Hexo
  - npm install hexo@beta -g
  # Clone the repository
  - git clone https://github.com/susutou/susutou.github.io.git .deploy

script:
  - hexo generate
  - hexo deploy

branches:
  only:
    - master
